Add CI improvements, tests, and data handling refinements (#1)
* Create python-app.yml

* Add .gittatributes for test data

* Extend gitatributes for tests folder

* Add lfs test data files

* Add:

 - pyproject.toml: Extend dependencies for pytest and reading test files
 - test_main.py: pytest test file
 - mdl_hist.pyx: change function parameter `K_max` to match with documentation

* Remove: python version 3.14

* Add: LFS support to donwload test files

* Change data types:

- unsigned long to unsigned long long: With line ```    n_e = np.zeros(len(candidates), dtype=np.uint64)  # Include E+1
``` we assume unsigned long long for  n_e, so we have to change the data types
- int K_max to long long K_max: related to upper dot I have to change this to long long

* Split in pytest build of package and test

* Add: example picture to demonstrate functonality

* Remove macOs arm. because  results are partially wrong:

```
 ============================= test session starts ==============================
platform darwin -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0
rootdir: /Users/runner/work/MDL-Density-Histogram/MDL-Density-Histogram
configfile: pyproject.toml
plugins: xdist-3.8.0
collected 12 items
test_main.py .........F..                                                [100%]
=================================== FAILURES ===================================
________________________________ test_gmm5_id_2 ________________________________
    def test_gmm5_id_2():
        gmmX_ds = pd.read_parquet("gmm5_samples.parquet.brotli")
        gmmX_mdl_lower_bins = pd.read_parquet("gmm5_samples_MDL_lower_bins.parquet.brotli")
        id = 2

        assert all(np.unique(gmmX_ds["dataset_id"]) == np.unique(gmmX_mdl_lower_bins["dataset_id"])), "The number of dataset ids must equal"
        dataset = gmmX_ds[gmmX_ds["dataset_id"] == id]["value"].to_numpy()
        lower_bins_true = gmmX_mdl_lower_bins[gmmX_mdl_lower_bins["dataset_id"] == id]["lower_bin"].to_numpy()
        lower_bins_pred = mdl_optimal_histogram(dataset, K_max=K_max, epsilon=epsilon)

>       np.testing.assert_array_almost_equal(lower_bins_pred, lower_bins_true, decimal=5)
E       AssertionError:
E       Arrays are not almost equal to 5 decimals
E
E       (shapes (33,), (31,) mismatch)
E        ACTUAL: array([-10.87891,  -8.92891,  -8.02891,  -7.32891,  -6.62891,  -5.32891,
E               -4.72891,  -4.42891,  -4.22891,  -4.12891,  -3.92891,  -3.72891,
E               -3.62891,  -3.52891,  -3.32891,  -2.82891,  -2.62891,  -2.52891,...
E        DESIRED: array([-10.87891,  -8.92891,  -8.02891,  -7.32891,  -6.62891,  -5.32891,
E               -4.72891,  -4.42891,  -4.22891,  -4.12891,  -3.92891,  -3.72891,
E               -3.52891,  -3.32891,  -2.82891,  -2.52891,  -2.42891,  -2.22891,...
test_main.py:131: AssertionError
=========================== short test summary info ============================
FAILED test_main.py::test_gmm5_id_2 - AssertionError:
Arrays are not almost equal to 5 decimals
(shapes (33,), (31,) mismatch)
 ACTUAL: array([-10.87891,  -8.92891,  -8.02891,  -7.32891,  -6.62891,  -5.32891,
        -4.72891,  -4.42891,  -4.22891,  -4.12891,  -3.92891,  -3.72891,
        -3.62891,  -3.52891,  -3.32891,  -2.82891,  -2.62891,  -2.52891,...
 DESIRED: array([-10.87891,  -8.92891,  -8.02891,  -7.32891,  -6.62891,  -5.32891,
        -4.72891,  -4.42891,  -4.22891,  -4.12891,  -3.92891,  -3.72891,
        -3.52891,  -3.32891,  -2.82891,  -2.52891,  -2.42891,  -2.22891,...
=================== 1 failed, 11 passed in 228.35s (0:03:48) ===================
```

* Add:

Build and test for macos on intel and windows and linux on arm

* Remove windows-11-arm runner:

```
  CMake Error at CMakeLists.txt:22 (project):
    Generator

      Visual Studio 15 2017 Win64

    could not find any instance of Visual Studio.

  -- Configuring incomplete, errors occurred!
  error: command 'C:\\Program Files\\CMake\\bin\\cmake.EXE' failed with exit code 1
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow
error: failed-wheel-build-for-install

Failed to build installable wheels for some pyproject.toml based project
```

* Add application test badge

* Remove macos and windows arm, cause tests do not work

* Store all bad runners in one, to track if they will work in future.

* Rename the bad runner to bad runner

* Do not need to run on pull requests

* Runner work know, removed them which i doo not need. We can go to the next  minor version.